defaults:
  - model/gr00t_16@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - _self_
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:REPO_PATH}/examples/embodiment/config

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: sft
  logger:
    log_path: '../results'
    project_name: rlinf
    experiment_name: 'gr00t_16_sft_libero'
    logger_backends: ['tensorboard']

  max_epochs: 100000
  max_steps: 20000
  val_check_interval: -1
  save_interval: 2000

data:
  train_data_paths: ${oc.env:GR00T_SFT_DATASET_PATH,/path/to/Gr00t_16-libero-Spatial-dataset}
  action_key: 'action'

algorithm:
  adv_type: gae

actor:
  group_name: 'ActorGroup'
  training_backend: 'fsdp'
  micro_batch_size: 2
  global_batch_size: 64
  seed: 42

  model:
    precision: 'bf16'
    model_path: ${oc.env:GR00T_SFT_MODEL_PATH,nvidia/GR00T-N1.7-3B}
    model_type: 'gr00t_1_6_sft'
    num_action_chunks: 16
    embodiment_tag: 'libero_panda'
    add_value_head: true
    denoising_steps: 4
    no_split_modules:
      - 'Qwen3DecoderLayer'
      - 'Siglip2EncoderLayer'
      - 'FlowMatchingActionHeadForRLActionPrediction'
      - 'TimestepEncoder'
      - 'TimestepEmbedding'
      - 'ValueHead'
      - 'ExploreNoiseNet'

  optim:
    lr: 1.0e-4
    value_lr: 1.0e-4
    lr_scheduler: 'cosine'
    total_training_steps: 20000
    lr_warmup_steps_ratio: 0.05
    min_lr: 0.0
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 1.0e-5
    clip_grad: 1.0

  fsdp_config:
    strategy: 'fsdp'
    sharding_strategy: 'full_shard'
    use_orig_params: false
    gradient_checkpointing: false
    mixed_precision:
      param_dtype: '${actor.model.precision}'
      reduce_dtype: '${actor.model.precision}'
      buffer_dtype: '${actor.model.precision}'

reward:
  use_reward_model: false

critic:
  use_critic_model: false
